#!/usr/bin/env bash
# scripts/setup_module1_content.sh
# Creates: <repo_root>/contents/module1/ with ehr_demo + practice files.
#
# Run:
#   bash scripts/setup_module1_content.sh
#
# Options:
#   --force        Rebuild module1 from scratch (deletes existing module1 folder)
#   --base PATH    Override base folder that contains module1 (default: <repo_root>/contents)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

BASE="${REPO_ROOT}/contents"
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base)
      BASE="${2:?Missing value for --base}"
      if [[ "${BASE}" != /* ]]; then
        BASE="${REPO_ROOT}/${BASE}"
      fi
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      sed -n '1,60p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

MOD1="${BASE%/}/module1"
RAW="${MOD1}/ehr_demo/raw"
DOCS="${MOD1}/ehr_demo/docs"
RESULTS="${MOD1}/ehr_demo/results"
PRACTICE="${MOD1}/practice"

min_lines_check() {
  local path="$1"
  local min="${2:-20}"
  local base
  base="$(basename "$path")"
  if [[ "$base" == "hello.sh" ]]; then
    return 0
  fi
  local n
  n="$(wc -l < "$path" | tr -d ' ')"
  if [[ "$n" -lt "$min" ]]; then
    echo "ERROR: '$path' has $n lines (< $min). Add more lines." >&2
    exit 1
  fi
}

write_file() {
  local path="$1"
  cat > "$path"
  min_lines_check "$path" 20
}

write_file_allow_short() {
  local path="$1"
  cat > "$path"
}

if [[ -d "$MOD1" && "$FORCE" -eq 1 ]]; then
  rm -rf "$MOD1"
fi

if [[ -d "$MOD1" && "$FORCE" -ne 1 ]]; then
  echo "ERROR: '$MOD1' already exists. Re-run with --force to rebuild." >&2
  exit 1
fi

mkdir -p "$RAW" "$DOCS" "$RESULTS" "$PRACTICE"

# ---------- README (>=20)
write_file "${MOD1}/README.md" <<'EOF'
# Module 1 Practice Data (BIO2110)

This folder is generated by an instructor script.
Students: you do NOT need to run the generator.

What this module contains:
- ehr_demo/raw/      synthetic CSV tables for previewing and navigation practice
- ehr_demo/docs/     a data dictionary and short notes file
- ehr_demo/results/  empty output folder (you will create files here later)
- practice/          files for safe file operations (mkdir, touch, cp, mv, rm)

Beginner routine (repeat often):
1) pwd   (Where am I?)
2) ls -F (What is here?)
3) Move with cd, then re-check pwd and ls -F

Professional habit:
- Never edit “raw” data in place.
- Copy raw files into a workspace before changing anything.

AI-aware note:
- You may ask AI tools to explain errors or commands.
- You must verify everything by running commands yourself.
- Never paste private or sensitive data into AI tools.

EOF

# ---------- patients.csv (>=20 lines)
write_file "$RAW/patients.csv" <<'EOF'
patient_id,sex,age_group,zip3
P001,F,40-49,112
P002,M,30-39,112
P003,F,50-59,070
P004,M,20-29,070
P005,F,60-69,100
P006,M,40-49,100
P007,F,30-39,112
P008,M,50-59,070
P009,F,20-29,070
P010,M,60-69,100
P011,F,40-49,112
P012,M,30-39,112
P013,F,50-59,070
P014,M,20-29,070
P015,F,60-69,100
P016,M,40-49,100
P017,F,30-39,112
P018,M,50-59,070
P019,F,20-29,070
P020,M,60-69,100
P021,F,40-49,112
EOF

# ---------- visits.csv (>=20 lines)
write_file "$RAW/visits.csv" <<'EOF'
visit_id,patient_id,visit_date,visit_type
V0001,P001,2026-02-01,Outpatient
V0002,P002,2026-02-01,Outpatient
V0003,P003,2026-02-02,ED
V0004,P004,2026-02-02,Outpatient
V0005,P005,2026-02-03,Inpatient
V0006,P006,2026-02-03,Outpatient
V0007,P007,2026-02-04,Outpatient
V0008,P008,2026-02-04,ED
V0009,P009,2026-02-05,Outpatient
V0010,P010,2026-02-05,Inpatient
V0011,P011,2026-02-06,Outpatient
V0012,P012,2026-02-06,Outpatient
V0013,P013,2026-02-07,ED
V0014,P014,2026-02-07,Outpatient
V0015,P015,2026-02-08,Inpatient
V0016,P016,2026-02-08,Outpatient
V0017,P017,2026-02-09,Outpatient
V0018,P018,2026-02-09,ED
V0019,P019,2026-02-10,Outpatient
V0020,P020,2026-02-10,Inpatient
V0021,P021,2026-02-11,Outpatient
EOF

# ---------- data_dictionary.txt (>=20)
write_file "$DOCS/data_dictionary.txt" <<'EOF'
Data dictionary (teaching demo) — Module 1 ehr_demo

Files are synthetic and designed for beginner-friendly shell practice.

File: patients.csv
- patient_id : P### synthetic patient identifier
- sex        : F or M (simplified for teaching)
- age_group  : categorical age band (20-29, 30-39, etc.)
- zip3       : first 3 digits of ZIP code (coarse location)

File: visits.csv
- visit_id   : V#### synthetic visit identifier
- patient_id : links to patients.csv patient_id
- visit_date : YYYY-MM-DD visit date
- visit_type : Outpatient, ED, Inpatient

Suggested beginner checks:
- Preview headers:
  head patients.csv
  head visits.csv

- Confirm row counts:
  wc -l patients.csv
  wc -l visits.csv

- Practice safe copying:
  cp ehr_demo/raw/patients.csv practice/patients_copy.csv

Reminder:
- These files are for learning. Do not treat them as real clinical data.

EOF

# ---------- docs/notes.txt (>=20)
write_file "$DOCS/notes.txt" <<'EOF'
Module 1 notes (students)

Goals:
1) Learn what folders and files are in the shell.
2) Learn how to navigate safely using cd, pwd, ls.
3) Learn how to preview data with head, tail, less.
4) Learn safe file operations: mkdir, touch, cp, mv, rm (carefully).

Rules that prevent confusion:
- The shell is case-sensitive.
- Spaces matter.
- Relative paths depend on where you are.

If anything fails:
1) Run: pwd
2) Run: ls -F
3) Re-try the command slowly.

AI-aware:
- Use AI as a tutor, not an autopilot.
- Never run a command you cannot explain.
- Verify by running commands yourself and checking output.

EOF

# ---------- practice/notes.txt (>=20)
write_file "$PRACTICE/notes.txt" <<'EOF'
Practice workspace (Module 1)

This folder is for you to create and delete files safely.

Try these (examples):
1) Create a folder:
   mkdir sandbox

2) Create an empty file:
   touch sandbox/todo.txt

3) Copy a raw file into practice:
   cp ../ehr_demo/raw/patients.csv sandbox/patients_working.csv

4) Rename a file:
   mv sandbox/patients_working.csv sandbox/patients_for_notes.csv

5) Delete ONLY in practice:
   rm sandbox/patients_for_notes.csv

Safety:
- Before any delete, run pwd and ls -F.
- Do not delete in ehr_demo/raw.

EOF

# ---------- practice/hello.sh (short allowed)
write_file_allow_short "$PRACTICE/hello.sh" <<'EOF'
#!/usr/bin/env bash
echo "Hello from Module 1 practice!"
echo "If this runs, your execute permission works."
EOF
chmod +x "$PRACTICE/hello.sh"

echo "Module 1 generated at: $MOD1"
#echo "Suggested checks:"
#echo "  ls -R \"$MOD1\""
#echo "  head \"$RAW/patients.csv\""
#echo "  wc -l \"$RAW/visits.csv\""


# ---------- Module 1 student-facing lab setup script (Google Cloud Shell)
mkdir -p "${MOD1}/scripts"

write_file "${MOD1}/scripts/setup_module1_lab_activity.sh" <<'EOF'
#!/usr/bin/env bash
# setup_module1_lab_activity.sh
#
# Module 1 Lab (Google Cloud Shell) setup
# - Creates/refreshes: contents/module1/lab_activity/
# - Seeds a small "ehr_demo" dataset for safe practice (raw + docs)
# - Creates a separate practice area for cp/mv/rm drills
#
# Safe to re-run. Designed so students run ONE command, then practice.
#
# Recommended run command (from repo root):
#   bash contents/module1/scripts/setup_module1_lab_activity.sh
#
# If you haven't cloned the repo yet (one-liner option):
#   git clone https://github.com/Mai-Zahran/BIO2110-UNIX-shell-ForStudents.git && \
#   bash BIO2110-UNIX-shell-ForStudents/contents/module1/scripts/setup_module1_lab_activity.sh

set -euo pipefail

REPO_URL="https://github.com/Mai-Zahran/BIO2110-UNIX-shell-ForStudents.git"
REPO_DIR_DEFAULT="$HOME/BIO2110-UNIX-shell-ForStudents"

echo "== BIO2110 • Module 1 Lab Setup (Google Cloud Shell) =="
echo

# --------- 1) Find the repo ---------
# Primary: derive repo root from where THIS script lives:
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CANDIDATE_REPO="$(cd "${SCRIPT_DIR}/../../.." && pwd)"  # scripts -> module1 -> contents -> repo

REPO_DIR=""

if [[ -d "${CANDIDATE_REPO}/contents/module1" ]]; then
  REPO_DIR="${CANDIDATE_REPO}"
elif [[ -d "./contents/module1" ]]; then
  REPO_DIR="$(pwd)"
elif [[ -d "${REPO_DIR_DEFAULT}/contents/module1" ]]; then
  REPO_DIR="${REPO_DIR_DEFAULT}"
else
  echo "[1/4] Course repo not found here."
  echo "      Cloning into: ${REPO_DIR_DEFAULT}"
  git clone "${REPO_URL}" "${REPO_DIR_DEFAULT}"
  REPO_DIR="${REPO_DIR_DEFAULT}"
fi

MODULE1_DIR="${REPO_DIR}/contents/module1"

if [[ ! -d "${MODULE1_DIR}" ]]; then
  echo "ERROR: Expected Module 1 folder not found at:"
  echo "  ${MODULE1_DIR}"
  echo "Tell your instructor (repo structure may have changed)."
  exit 1
fi

echo "[1/4] Using repo at:"
echo "      ${REPO_DIR}"
echo

echo "[2/4] Attempting: git pull (ok if it fails in a restricted environment)"
( cd "${REPO_DIR}" && git pull ) >/dev/null 2>&1 || true
echo "      Done."
echo

# --------- helpers ---------
ensure_min_lines() {
  # Ensure a file has at least N lines by appending harmless filler lines.
  # Usage: ensure_min_lines <file> <min_lines>
  local f="$1"
  local min="${2:-20}"
  local n
  n="$(wc -l < "$f" | tr -d ' ')"
  if [[ "$n" -ge "$min" ]]; then
    return 0
  fi
  local i=$((n+1))
  while [[ "$i" -le "$min" ]]; do
    echo "# filler line ${i} (keeps file >= ${min} lines for grading/tools)" >> "$f"
    i=$((i+1))
  done
}

write_text() {
  # write_text <file>  (stdin content)
  local f="$1"
  cat > "$f"
  ensure_min_lines "$f" 20
}

# --------- 3) Create lab workspace ---------
LAB_DIR="${MODULE1_DIR}/lab_activity"
EHR_DIR="${LAB_DIR}/ehr_demo"
RAW_DIR="${EHR_DIR}/raw"
DOCS_DIR="${EHR_DIR}/docs"
PRACTICE_DIR="${LAB_DIR}/practice"
TMP_DIR="${LAB_DIR}/tmp"
TAB_DIR="${LAB_DIR}/tab_practice"

echo "[3/4] Creating/refreshing lab workspace at:"
echo "      ${LAB_DIR}"
mkdir -p "${RAW_DIR}" "${DOCS_DIR}" "${PRACTICE_DIR}/work" "${PRACTICE_DIR}/results" "${PRACTICE_DIR}/docs" "${TMP_DIR}" "${TAB_DIR}"

# Clean only the *practice* area
rm -rf "${PRACTICE_DIR}/work" "${PRACTICE_DIR}/results" "${PRACTICE_DIR}/docs"
mkdir -p "${PRACTICE_DIR}/work" "${PRACTICE_DIR}/results" "${PRACTICE_DIR}/docs"

# --------- 4) Seed demo data ---------
PAT_N=250   # number of patient rows (not counting header)
PAT_FILE="${RAW_DIR}/patients.csv"
{
  echo "patient_id,age,sex,condition"
  for i in $(seq -w 1 "${PAT_N}"); do
    age=$(( (10#$i % 70) + 18 ))
    sex=$((10#$i % 2))
    if [[ "${sex}" -eq 0 ]]; then s="F"; else s="M"; fi
    case $((10#$i % 5)) in
      0) c="hypertension" ;;
      1) c="type2_diabetes" ;;
      2) c="asthma" ;;
      3) c="hyperlipidemia" ;;
      4) c="migraine" ;;
    esac
    echo "P${i},${age},${s},${c}"
  done
} > "${PAT_FILE}"

VIS_N=250
VIS_FILE="${RAW_DIR}/visits.csv"
{
  echo "visit_id,patient_id,visit_date,site,reason"
  for i in $(seq -w 1 "${VIS_N}"); do
    pid="P$(printf "%03d" $(( (10#$i % PAT_N) + 1 )))"
    month=$(( (10#$i % 12) + 1 ))
    day=$(( (10#$i % 27) + 1 ))
    date="$(printf "2025-%02d-%02d" "${month}" "${day}")"
    case $((10#$i % 4)) in
      0) site="ED" ;;
      1) site="clinic" ;;
      2) site="telehealth" ;;
      3) site="lab" ;;
    esac
    case $((10#$i % 6)) in
      0) reason="follow_up" ;;
      1) reason="new_symptoms" ;;
      2) reason="med_refill" ;;
      3) reason="lab_review" ;;
      4) reason="vaccination" ;;
      5) reason="annual_physical" ;;
    esac
    echo "V${i},${pid},${date},${site},${reason}"
  done
} > "${VIS_FILE}"

write_text "${DOCS_DIR}/data_dictionary.txt" <<'DD'
DATA DICTIONARY (demo) — Module 1 Lab

patients.csv
- patient_id : patient identifier (string like P001)
- age        : age in years (integer)
- sex        : F/M (string)
- condition  : simple synthetic condition label (string)

visits.csv
- visit_id   : visit identifier (string like V001)
- patient_id : links to patients.csv patient_id (string)
- visit_date : visit date YYYY-MM-DD (string)
- site       : ED / clinic / telehealth / lab (string)
- reason     : short reason code (string)

Notes:
- This dataset is synthetic (not real).
- Always preview first: head, less.
- Always keep raw files unchanged during learning.
DD

BIG="${RAW_DIR}/big_log.txt"
: > "${BIG}"
i=1
while [[ "${i}" -le 1200 ]]; do
  printf "2026-02-17T10:%02d:%02dZ device=ECG value=%d\n" $((i%60)) $((i%60)) $((i%1000)) >> "${BIG}"
  i=$((i+1))
done
# big_log is already >20 lines by design

# --------- Controlled learning traps ---------
mkdir -p "${LAB_DIR}/EHR_Demo"
write_text "${LAB_DIR}/EHR_Demo/CASE_NOTE.txt" <<'CN'
This folder exists to demonstrate case sensitivity.

Try:
- ls
- ls ehr_demo
- ls EHR_Demo

You should see that:
- ehr_demo and EHR_Demo are different names.
- The shell treats them as different paths.

Reminder:
- Case matters.
- Spelling matters.
- Slashes matter.

(Use pwd and ls -F constantly.)
CN

mkdir -p "${TMP_DIR}/is_a_directory"
write_text "${TMP_DIR}/delete_me.txt" <<'DEL'
This file exists so you can practice deleting safely.

Rules:
1) Only delete inside lab_activity/tmp or lab_activity/practice.
2) Before deleting, run:
   - pwd
   - ls -F
3) Then delete with:
   rm delete_me.txt

If you delete the wrong thing:
- STOP
- Tell your instructor
- Do not try random fixes

This file is safe to delete.
DEL

# --------- Tab completion practice ---------
mkdir -p "${TAB_DIR}"

mkdir -p "${TAB_DIR}/very_long_directory_name_for_tab_practice"
mkdir -p "${TAB_DIR}/very_long_directory_name_for_tab_prep"
mkdir -p "${TAB_DIR}/very_long_directory_name_for_tab_project"

write_text "${TAB_DIR}/patient_001_notes.txt" <<'P1N'
Patient 001 — notes (sample)

Goal:
Practice tab completion and file preview commands.

Try:
- ls -F
- head patient_001_notes.txt
- less patient_001_notes.txt

This file is intentionally longer than you need.
Do not memorize it.
Use tools to navigate it.

End of note.
P1N

write_text "${TAB_DIR}/patient_001_raw.txt" <<'P1R'
patient_id,age,sex
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P001,44,F
P1R

write_text "${TAB_DIR}/patient_002_notes.txt" <<'P2N'
Patient 002 — notes (sample)

Goal:
Practice tab completion with similar filenames.

Try:
- cat patient_002_notes.txt
- head patient_002_notes.txt
- less patient_002_notes.txt

Then compare:
- patient_001_notes.txt
- patient_002_notes.txt

Notice the naming pattern.
P2N

write_text "${TAB_DIR}/patient_002_raw.txt" <<'P2R'
patient_id,age,sex
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P002,51,M
P2R

# A slightly longer patients.csv in tab_practice (>=20 lines)
{
  echo "patient_id,age,sex"
  echo "P001,44,F"
  echo "P002,51,M"
  echo "P003,39,F"
  echo "P004,62,M"
  echo "P005,28,F"
  echo "P006,47,M"
  echo "P007,35,F"
  echo "P008,58,M"
  echo "P009,41,F"
  echo "P010,66,M"
  echo "P011,22,F"
  echo "P012,49,M"
  echo "P013,33,F"
  echo "P014,57,M"
  echo "P015,26,F"
  echo "P016,45,M"
  echo "P017,38,F"
  echo "P018,52,M"
  echo "P019,29,F"
  echo "P020,63,M"
} > "${TAB_DIR}/patients.csv"
ensure_min_lines "${TAB_DIR}/patients.csv" 20

cp "${TAB_DIR}/patients.csv" "${TAB_DIR}/patients_notes.csv"
cp "${TAB_DIR}/patients.csv" "${TAB_DIR}/patients_preview.csv"

write_text "${TAB_DIR}/very_long_directory_name_for_tab_practice/patients_for_notes.csv" <<'L1'
patient_id,note
P001,Follow-up scheduled.
P002,New medication started.
P003,Patient asked about labs.
P004,Telehealth visit planned.
P005,Reminder: hydrate.
P006,Bring medication list.
P007,Discuss sleep habits.
P008,Review BP readings.
P009,Confirm pharmacy.
P010,Annual physical due.
P011,Lab results pending.
P012,Follow-up in 2 weeks.
P013,Update insurance info.
P014,Allergies reviewed.
P015,Discuss diet plan.
P016,Exercise recommendation.
P017,Vaccination update.
P018,Stress management tips.
P019,Refill request noted.
P020,Return if symptoms worsen.
L1

write_text "${TAB_DIR}/very_long_directory_name_for_tab_practice/patients_for_preview.csv" <<'L2'
patient_id,preview
P001,OK
P002,OK
P003,OK
P004,OK
P005,OK
P006,OK
P007,OK
P008,OK
P009,OK
P010,OK
P011,OK
P012,OK
P013,OK
P014,OK
P015,OK
P016,OK
P017,OK
P018,OK
P019,OK
P020,OK
L2

write_text "${TAB_DIR}/very_long_directory_name_for_tab_practice/patients_for_practice.csv" <<'L3'
patient_id,practice
P001,yes
P002,yes
P003,yes
P004,yes
P005,yes
P006,yes
P007,yes
P008,yes
P009,yes
P010,yes
P011,yes
P012,yes
P013,yes
P014,yes
P015,yes
P016,yes
P017,yes
P018,yes
P019,yes
P020,yes
L3

mkdir -p "${TAB_DIR}/very_long_directory_name_for_tab_practice/subfolder_with_another_long_name_for_more_tab_practice"
write_text "${TAB_DIR}/very_long_directory_name_for_tab_practice/subfolder_with_another_long_name_for_more_tab_practice/README_tab.txt" <<'RT'
README (Tab practice)

Goal:
Practice tab completion on deep paths.

Try:
- cd tab_practice
- cd very_long_directory_name_for_tab_practice/sub<TAB>
- ls -F
- less README_tab.txt

Tips:
- If tab is ambiguous, press Tab twice.
- Use ls -F to see which items are folders.

End.
RT

write_text "${LAB_DIR}/CHECKLIST.txt" <<'CL'
Module 1 Lab Checklist (open with: less CHECKLIST.txt)

Evidence routine (always):
1) pwd      (Where am I?)
2) ls -F    (What exists here?)
3) Compare command text to reality (names, slashes, capitalization)

You will practice:
- pwd, ls, ls -F, ls -l, ls -ltr
- cd, cd .., cd ~, cd -
- absolute vs relative paths
- head, tail, less, cat (only for small files)
- mkdir -p, touch, cp, cp -r, mv, rm (ONLY inside lab_activity/practice or lab_activity/tmp)
- Tab completion drills (tab_practice/)

Safety:
- Never rm in ehr_demo/raw
- If unsure, STOP and ask for help

Done when:
- You can navigate confidently and explain what each command did.
CL

echo "[4/4] Done."
echo
echo "Next steps:"
echo "  cd \"${LAB_DIR}\""
echo "  pwd"
echo "  ls -F"
echo
EOF

#chmod +x "${MOD1}/scripts/setup_module1_lab_activity.sh"

